// ==UserScript==
// @name         useascript
// @namespace    https://dra.vin/
// @version      0.9.0
// @description  A compendium of userscripts for the Web
// @author       Avindra Goolcharan
// @match        *://*/*
// @updateURL    https://dra.vin/useascript/useascript.meta.js
// ==/UserScript==
(()=>{var J=Object.create;var $=Object.defineProperty;var K=Object.getOwnPropertyDescriptor;var Q=Object.getOwnPropertyNames;var V=Object.getPrototypeOf,Y=Object.prototype.hasOwnProperty;var C=t=>e=>{var o=t[e];if(o)return o();throw new Error("Module not found in bundle: "+e)};var r=(t,e)=>()=>(t&&(e=t(t=0)),e);var u=(t,e)=>()=>(e||t((e={exports:{}}).exports,e),e.exports);var X=(t,e,o,n)=>{if(e&&typeof e=="object"||typeof e=="function")for(let a of Q(e))!Y.call(t,a)&&a!==o&&$(t,a,{get:()=>e[a],enumerable:!(n=K(e,a))||n.enumerable});return t};var h=(t,e,o)=>(o=t!=null?J(V(t)):{},X(e||!t||!t.__esModule?$(o,"default",{value:t,enumerable:!0}):o,t));var q=u(()=>{if(/\/research\/search_the_collection_database\/search_object_(?:details|image).aspx/.test(location.pathname)){let t=new URLSearchParams(location.search.substring(1)),e=t.get("objectId")||t.get("objectid");e&&(location.href=`/collection/search?keyword=${e}`)}});var E=u(()=>{var Z=/s\d+-([cp])/;if(!location.href.includes("4096")){let t=location.href.replace(Z,"s4096-$1");t!==location.href&&location.replace(t);let e=location.href.replace(/w\d+-h\d+/,"w4096-h4096");e!==location.href&&location.replace(e)}});var y,i,c,l=r(()=>{y=t=>new Promise(e=>setTimeout(e,t)),i=t=>{window.onpopstate=t;for(let e of["pushState","replaceState"])window.history[e]=new Proxy(window.history[e],{apply:(o,n,a)=>(t(),o.apply(n,a))});t()},c=(t,e,o=1e4)=>{let n=setInterval(()=>{let a=t();if(a)return clearInterval(n),e(a)},200);setTimeout(()=>clearInterval(n),o)}});var te={};async function ee(){let t=/\/([^/]+)\/([^/]+)\/blob\/(.+)\/(.+)/,e=location.pathname.match(t);if(e){let o=document.querySelector("#repos-sticky-header div[class^=prc-ButtonGroup]");if(o){let[,n,a,p,s]=e,g=`https://cdn.jsdelivr.net/gh/${n}/${a}@${p}/${s}`,d=document.createElement("a");d.href=g,d.textContent="JsDelivr",d.className="btn-sm btn BtnGroup-item",o.appendChild(d)}}else if(/\/compare\//.test(location.pathname)){let o=()=>document.querySelectorAll("#commits_bucket .Details:not(.branch-action-item)"),n=0,a;do{if(a=o(),a.length>0)break;await y(500)}while(++n<10);let p=document.querySelector(".range-editor");if(p){let s=document.createElement("button");s.textContent=`Show ${a.length} commits`,s.onclick=()=>{a=o();let g=Array.from(a).map(d=>d.querySelector("p").textContent.trim().replace(/[\s\n…]+$/g,""));console.log(g,g.join(`
`))},p.appendChild(s)}}k=!1}var k,N=r(()=>{l();k=!1;i(async()=>{k||(k=!0,await y(1e3),setTimeout(ee,1e3))})});var ne={};var T,oe,j=r(()=>{l();i(()=>{let t=new URLSearchParams(location.search.substring(1)),e;for(let[o]of t.entries())e=o;if(t.get("tbm")==="isch"){t.sort();let o=t.get("q");if(o&&e!=="q"){t.delete("q"),t.set("q",o);let n=`${location.pathname}?${t.toString()}`;location.href=n}}});T=t=>{let e=t.getElementsByTagName("a");for(let o=e[0],n=1;o;n++)o.removeAttribute("data-jsarwt"),o=e[n]},oe=t=>{let e=t.target;T(e)};document.addEventListener("load",T(document.body),!1);document.body.addEventListener("AutoPagerize_DOMNodeInserted",oe,!1)});var I=u(()=>{var ae=`
	.copyright-warning,
	.gita-side-content > div > div:nth-child(2),
	.gita-side-content > div > div:nth-child(3),
	.search-text,
	.gsib_b {
		display:none;
	}

	body {
		background-color: #131b42;
		background-image: none;
	}
`,v=document.createElement("style");v.type="text/css";v.innerText=ae;document.head.appendChild(v);var w=document.querySelector(".bg-verse-audio audio");if(w){w.onended=()=>{let t=document.querySelector(".verse-navigator a.next-element"),e=Array.from(document.querySelectorAll(".actual-verse-navigator a")),o=document.querySelector(".actual-verse-navigator a.active");e[e.length-1]===o?document.querySelector(".chapter-navigator a.next-element").click():t.click()};try{w.play()}catch{}}});var L=u(()=>{var ce={childList:!0,subtree:!0},se=()=>{let t=document.body.lastChild;t.firstChild&&t.firstChild.id==="scrollview"&&t.remove()},re=new MutationObserver(se);re.observe(document.body,ce)});var _=u(()=>{var ie=`
main {
background-color: rebeccapurple;
}
#top {
background-color: wheat;
}
header div:last-child {
background-color: blanchedalmond;
}
header div:nth-child(2) {
display:none;
}
#footer {
background-color: #dfbf3f;
}
footer.mt4 {
margin-top:0;
}
[role="tabpanel"] {
background-color:#ffd381;
}
#main > div > div:first-child {
background-color:#ffdae5;
}
`;document.head.appendChild(Object.assign(document.createElement("style"),{type:"text/css",innerText:ie}));var b=document.querySelector('[aria-label="Package sidebar"]'),B=document.createElement("ul"),le=(t,e)=>{let o=document.createElement("li"),n=document.createElement("a");return n.href=e,n.textContent=t,o.append(n),o};function de(){let t=document.title.substring(0,document.title.length-6),e=[["npmgraph",`https://npmgraph.js.org/?q=${t}`],["Bundlephobia",`https://bundlephobia.com/package/${t}`],["anvaka",`https://npm.anvaka.com/#/view/2d/${t}`],["Packagephobia",`https://packagephobia.com/result?p=${t}`],["pkg-size.dev",`https://pkg-size.dev/${t}`],["npm-stat",`https://npm-stat.com/charts.html?package=${t}`],["deps.dev",`https://deps.dev/npm/${t}`],["npmx",`https://npmx.dev/package/${t}`],["socket.dev",`https://socket.dev/npm/package/${t}`],["snyk",`https://snyk.io/advisor/npm-package/${t}`]];for(let[o,n]of e)B.append(le(o,n));b.prepend(B),b.prepend(Object.assign(document.createElement("h3"),{textContent:"Analyze",className:"c84e15be f5 mt2 pt2 mb0"}))}if(b){for(let t of["https://bundlephobia.com/","https://npmgraph.js.org/","https://socket.dev/npm/package","https://snyk.io/advisor/npm-package"]){let e=b.querySelector(`[href^="${t}"]`);e&&e.remove()}de()}});var ue={};function x(t){if(["/user","/r"].includes(O))for(let e of t.querySelectorAll("a")){let o=e.getAttribute("href");if(!o)return;if(e.title&&o!=="/s"){let n=document.createElement("span");n.textContent=`(${e.title})`,n.className="titText",e.parentNode.insertBefore(n,e)}/\.(?:(jpe?|pn)g|gif|bmp)/.test(o)?(e.style.color="blue",e.style.fontWeight="bold",o===e.textContent&&(e.textContent="{Image}")):o.indexOf("/")===0||(/https?:\/\/(?:www\.)?reddit\.com/.test(o)?(e.className+=" favicon",e.style.color="crimson",e.style.backgroundImage='url("https://www.reddit.com/static/favicon.ico")'):/https?:\/\/(?:(www|music)\.)?youtube\.com/.test(o)?(e.className+=" favicon",e.style.color="red",e.style.backgroundImage='url("https://s.ytimg.com/yt/favicon.ico")',o===e.textContent&&(e.textContent="{watch on YouTube}")):/http:\/\/(?:www\.)?facebook\.com/.test(o)?(o.match(/[&?]id=(\d+)/)?e.innerHTML=`Profile: {${RegExp.$1}}`:e.pathname.match(/^\/([^?&#]+)/)&&(e.innerHTML=`Profile: ${RegExp.$1}`),e.className+=" favicon",e.style.color="darkBlue",e.style.backgroundImage='url("https://facebook.com/favicon.ico")'):/http:\/\/(?:www\.)?en\.wikipedia\.org\//.test(o)?(/\/wiki\/([^/]+)/.test(e.pathname)&&(e.textContent===o&&(e.innerHTML=""),e.innerHTML+=` <small>{${unescape(RegExp.$1).replace(/_/g," ")}}</small>`),e.style.color="black",e.style.backgroundImage='url("https://en.wikipedia.org/favicon.ico")',e.className+=" favicon"):e.href.startsWith(`${location.protocol}//${location.host}`)||(e.className+=" favicon",e.style.color="darkGreen",e.style.backgroundImage='url("https://upload.wikimedia.org/wikipedia/commons/0/0f/External-link-ltr-icon_Dark.png")',e.style.paddingRight="11px"))}}var me,S,pe,O,A=r(()=>{l();me=`
	.arrow.down {min-width:15px;min-height:14px;}
	.titText {font-size:smaller;color:darkSlateGray;font-weight:bold}
	.favicon {padding-right:17px;font-weight:bold;background-repeat:no-repeat;background-position:right center}
`,S=document.createElement("style");S.type="text/css";S.innerText=me;document.head.appendChild(S);pe=location.pathname.split(/(?!^)\//),O=pe[0];if(["/media"].includes(O)){let t=document.getElementsByTagName("img")[0],e=document.createElement("canvas"),o=e.getContext("2d");t.crossOrigin="anonymous",t=t.cloneNode(!0),t.onload=()=>{e.width=t.naturalWidth,e.height=t.naturalHeight,o.drawImage(t,0,0),e.toBlob(n=>{let a=URL.createObjectURL(n);location.href=a},"image/jpeg",1)}}c(()=>document.querySelector('[aria-controls="multireddits_section"]'),t=>{t.ariaExpanded==="true"&&t.click()});i(()=>{c(()=>document.querySelector("main"),x),c(()=>document.querySelector("shreddit-post-text-body"),x),c(()=>{let t=document.querySelector("shreddit-comment-tree");if(t&&t.scrollHeight>0)return t},x)})});var R,he,M=r(()=>{l();R=async t=>{c(()=>document.querySelector("header nav"),e=>he(e,t))},he=(t,e)=>{let n=t.firstChild.cloneNode(!0),a=document.createTextNode("\u{1F4DC}");n.firstChild.firstChild.replaceWith(a),a.parentNode.style.fontSize="25px";let s=n.querySelector("span");s&&(s.textContent="Useascript",Object.assign(s.style,{fontFamily:"monospace",fontSize:"smaller"})),n.removeAttribute("href"),n.onclick=e,t.prepend(n)}});var P,D=r(()=>{P=t=>{new MutationObserver(()=>{let e=t.querySelectorAll('a[href^="https://t.co"]');for(let o of e){let a=o.innerText.replace(/\s+/g,"").replace(/…$/,"");a.startsWith("http")&&(o.href=a,o.innerText=a)}}).observe(t,{childList:!0,subtree:!0})}});var f,z,H,U=r(()=>{l();D();f=!0,z=t=>{let e=t?"100%":"600px";c(()=>document.body.querySelector('[data-testid="primaryColumn"]'),o=>{o.style.maxWidth=e,c(()=>{let n=o.querySelector('[aria-level="1"]');if(n){let a=n.parentNode.parentNode;return P(a),a}},n=>n.style.maxWidth=e)}),c(()=>document.body.querySelector('[data-testid="sidebarColumn"]'),o=>o.style.display=f?"none":"block")},H=()=>(i(()=>{z(f)}),()=>{f=!f,z(f)})});var ge={};var fe,W,G=r(()=>{M();U();fe=H();R(()=>fe());W=document.createElement("style");W.textContent=`
	header > div {
		margin-left: 0 !important;
	}
`;document.head.appendChild(W)});var be={};var F=r(()=>{l();if(/^\/(?:c|user|@)\/?/.test(location.pathname)||document.getElementById("page-header")){let t=document.createElement("a"),e=ytInitialData.metadata.channelMetadataRenderer;t.textContent=e.externalId,t.href=e.channelUrl;let o=document.createElement("p");o.appendChild(t),c(()=>document.querySelector(".yt-page-header-view-model__page-header-title"),n=>n.nextElementSibling.prepend(o))}});var ye=C({"./britishmuseum.org/index.js":()=>Promise.resolve().then(()=>h(q())),"./ggpht.com/index.js":()=>Promise.resolve().then(()=>h(E())),"./github.com/index.js":()=>Promise.resolve().then(()=>(N(),te)),"./google.com/index.js":()=>Promise.resolve().then(()=>(j(),ne)),"./holy-bhagavad-gita.org/index.js":()=>Promise.resolve().then(()=>h(I())),"./instagram.com/index.js":()=>Promise.resolve().then(()=>h(L())),"./npmjs.com/index.js":()=>Promise.resolve().then(()=>h(_())),"./reddit.com/index.js":()=>Promise.resolve().then(()=>(A(),ue)),"./x.com/index.js":()=>Promise.resolve().then(()=>(G(),ge)),"./youtube.com/index.js":()=>Promise.resolve().then(()=>(F(),be))});var m;switch(location.host){case"github.com":case"x.com":case"mobile.x.com":{m=location.host.split(".").slice(-2).join(".");break}default:{let t=location.host.replace("www.","");switch(t){case"britishmuseum.org":case"holy-bhagavad-gita.org":case"google.com":case"ggpht.com":case"instagram.com":case"npmjs.com":case"reddit.com":case"youtube.com":m=t;default:/(ggpht|googleusercontent).com$/.test(t)&&(m="ggpht.com")}}}m&&(console.log("loading script",new Date,m),ye(`./${m}/index.js`));})();
